/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnavailableRouteImport } from './routes/unavailable'
import { Route as SubscriptionRequestsRouteImport } from './routes/subscription-requests'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PersonsRouteImport } from './routes/persons'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminsRouteImport } from './routes/admins'
import { Route as AccessEventsRouteImport } from './routes/access-events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonsIndexRouteImport } from './routes/persons.index'
import { Route as DevicesIndexRouteImport } from './routes/devices.index'
import { Route as AdminsIndexRouteImport } from './routes/admins.index'
import { Route as PersonsPersonIdRouteImport } from './routes/persons.$personId'
import { Route as PasswordResetRequestRouteImport } from './routes/password-reset.request'
import { Route as PasswordResetConfirmRouteImport } from './routes/password-reset.confirm'
import { Route as DevicesMonitoringRouteImport } from './routes/devices.monitoring'
import { Route as DevicesAdaptersRouteImport } from './routes/devices.adapters'
import { Route as BootstrapFirstAdminRouteImport } from './routes/bootstrap.first-admin'
import { Route as AdminsRolesRouteImport } from './routes/admins.roles'

const UnavailableRoute = UnavailableRouteImport.update({
  id: '/unavailable',
  path: '/unavailable',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRequestsRoute = SubscriptionRequestsRouteImport.update({
  id: '/subscription-requests',
  path: '/subscription-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsRoute = PersonsRouteImport.update({
  id: '/persons',
  path: '/persons',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRoute = AdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessEventsRoute = AccessEventsRouteImport.update({
  id: '/access-events',
  path: '/access-events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonsIndexRoute = PersonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PersonsRoute,
} as any)
const DevicesIndexRoute = DevicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevicesRoute,
} as any)
const AdminsIndexRoute = AdminsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminsRoute,
} as any)
const PersonsPersonIdRoute = PersonsPersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => PersonsRoute,
} as any)
const PasswordResetRequestRoute = PasswordResetRequestRouteImport.update({
  id: '/password-reset/request',
  path: '/password-reset/request',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetConfirmRoute = PasswordResetConfirmRouteImport.update({
  id: '/password-reset/confirm',
  path: '/password-reset/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesMonitoringRoute = DevicesMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DevicesRoute,
} as any)
const DevicesAdaptersRoute = DevicesAdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => DevicesRoute,
} as any)
const BootstrapFirstAdminRoute = BootstrapFirstAdminRouteImport.update({
  id: '/bootstrap/first-admin',
  path: '/bootstrap/first-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsRolesRoute = AdminsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-events': typeof AccessEventsRoute
  '/admins': typeof AdminsRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRouteWithChildren
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/persons': typeof PersonsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/subscription-requests': typeof SubscriptionRequestsRoute
  '/unavailable': typeof UnavailableRoute
  '/admins/roles': typeof AdminsRolesRoute
  '/bootstrap/first-admin': typeof BootstrapFirstAdminRoute
  '/devices/adapters': typeof DevicesAdaptersRoute
  '/devices/monitoring': typeof DevicesMonitoringRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/password-reset/request': typeof PasswordResetRequestRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/admins/': typeof AdminsIndexRoute
  '/devices/': typeof DevicesIndexRoute
  '/persons/': typeof PersonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-events': typeof AccessEventsRoute
  '/alerts': typeof AlertsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/subscription-requests': typeof SubscriptionRequestsRoute
  '/unavailable': typeof UnavailableRoute
  '/admins/roles': typeof AdminsRolesRoute
  '/bootstrap/first-admin': typeof BootstrapFirstAdminRoute
  '/devices/adapters': typeof DevicesAdaptersRoute
  '/devices/monitoring': typeof DevicesMonitoringRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/password-reset/request': typeof PasswordResetRequestRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/admins': typeof AdminsIndexRoute
  '/devices': typeof DevicesIndexRoute
  '/persons': typeof PersonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-events': typeof AccessEventsRoute
  '/admins': typeof AdminsRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/devices': typeof DevicesRouteWithChildren
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/persons': typeof PersonsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/subscription-requests': typeof SubscriptionRequestsRoute
  '/unavailable': typeof UnavailableRoute
  '/admins/roles': typeof AdminsRolesRoute
  '/bootstrap/first-admin': typeof BootstrapFirstAdminRoute
  '/devices/adapters': typeof DevicesAdaptersRoute
  '/devices/monitoring': typeof DevicesMonitoringRoute
  '/password-reset/confirm': typeof PasswordResetConfirmRoute
  '/password-reset/request': typeof PasswordResetRequestRoute
  '/persons/$personId': typeof PersonsPersonIdRoute
  '/admins/': typeof AdminsIndexRoute
  '/devices/': typeof DevicesIndexRoute
  '/persons/': typeof PersonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-events'
    | '/admins'
    | '/alerts'
    | '/audit-logs'
    | '/dashboard'
    | '/devices'
    | '/invite'
    | '/login'
    | '/persons'
    | '/profile'
    | '/settings'
    | '/subscription-requests'
    | '/unavailable'
    | '/admins/roles'
    | '/bootstrap/first-admin'
    | '/devices/adapters'
    | '/devices/monitoring'
    | '/password-reset/confirm'
    | '/password-reset/request'
    | '/persons/$personId'
    | '/admins/'
    | '/devices/'
    | '/persons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-events'
    | '/alerts'
    | '/audit-logs'
    | '/dashboard'
    | '/invite'
    | '/login'
    | '/profile'
    | '/settings'
    | '/subscription-requests'
    | '/unavailable'
    | '/admins/roles'
    | '/bootstrap/first-admin'
    | '/devices/adapters'
    | '/devices/monitoring'
    | '/password-reset/confirm'
    | '/password-reset/request'
    | '/persons/$personId'
    | '/admins'
    | '/devices'
    | '/persons'
  id:
    | '__root__'
    | '/'
    | '/access-events'
    | '/admins'
    | '/alerts'
    | '/audit-logs'
    | '/dashboard'
    | '/devices'
    | '/invite'
    | '/login'
    | '/persons'
    | '/profile'
    | '/settings'
    | '/subscription-requests'
    | '/unavailable'
    | '/admins/roles'
    | '/bootstrap/first-admin'
    | '/devices/adapters'
    | '/devices/monitoring'
    | '/password-reset/confirm'
    | '/password-reset/request'
    | '/persons/$personId'
    | '/admins/'
    | '/devices/'
    | '/persons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessEventsRoute: typeof AccessEventsRoute
  AdminsRoute: typeof AdminsRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  DashboardRoute: typeof DashboardRoute
  DevicesRoute: typeof DevicesRouteWithChildren
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  PersonsRoute: typeof PersonsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionRequestsRoute: typeof SubscriptionRequestsRoute
  UnavailableRoute: typeof UnavailableRoute
  BootstrapFirstAdminRoute: typeof BootstrapFirstAdminRoute
  PasswordResetConfirmRoute: typeof PasswordResetConfirmRoute
  PasswordResetRequestRoute: typeof PasswordResetRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unavailable': {
      id: '/unavailable'
      path: '/unavailable'
      fullPath: '/unavailable'
      preLoaderRoute: typeof UnavailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-requests': {
      id: '/subscription-requests'
      path: '/subscription-requests'
      fullPath: '/subscription-requests'
      preLoaderRoute: typeof SubscriptionRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons': {
      id: '/persons'
      path: '/persons'
      fullPath: '/persons'
      preLoaderRoute: typeof PersonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins': {
      id: '/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-events': {
      id: '/access-events'
      path: '/access-events'
      fullPath: '/access-events'
      preLoaderRoute: typeof AccessEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persons/': {
      id: '/persons/'
      path: '/'
      fullPath: '/persons/'
      preLoaderRoute: typeof PersonsIndexRouteImport
      parentRoute: typeof PersonsRoute
    }
    '/devices/': {
      id: '/devices/'
      path: '/'
      fullPath: '/devices/'
      preLoaderRoute: typeof DevicesIndexRouteImport
      parentRoute: typeof DevicesRoute
    }
    '/admins/': {
      id: '/admins/'
      path: '/'
      fullPath: '/admins/'
      preLoaderRoute: typeof AdminsIndexRouteImport
      parentRoute: typeof AdminsRoute
    }
    '/persons/$personId': {
      id: '/persons/$personId'
      path: '/$personId'
      fullPath: '/persons/$personId'
      preLoaderRoute: typeof PersonsPersonIdRouteImport
      parentRoute: typeof PersonsRoute
    }
    '/password-reset/request': {
      id: '/password-reset/request'
      path: '/password-reset/request'
      fullPath: '/password-reset/request'
      preLoaderRoute: typeof PasswordResetRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset/confirm': {
      id: '/password-reset/confirm'
      path: '/password-reset/confirm'
      fullPath: '/password-reset/confirm'
      preLoaderRoute: typeof PasswordResetConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/monitoring': {
      id: '/devices/monitoring'
      path: '/monitoring'
      fullPath: '/devices/monitoring'
      preLoaderRoute: typeof DevicesMonitoringRouteImport
      parentRoute: typeof DevicesRoute
    }
    '/devices/adapters': {
      id: '/devices/adapters'
      path: '/adapters'
      fullPath: '/devices/adapters'
      preLoaderRoute: typeof DevicesAdaptersRouteImport
      parentRoute: typeof DevicesRoute
    }
    '/bootstrap/first-admin': {
      id: '/bootstrap/first-admin'
      path: '/bootstrap/first-admin'
      fullPath: '/bootstrap/first-admin'
      preLoaderRoute: typeof BootstrapFirstAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admins/roles': {
      id: '/admins/roles'
      path: '/roles'
      fullPath: '/admins/roles'
      preLoaderRoute: typeof AdminsRolesRouteImport
      parentRoute: typeof AdminsRoute
    }
  }
}

interface AdminsRouteChildren {
  AdminsRolesRoute: typeof AdminsRolesRoute
  AdminsIndexRoute: typeof AdminsIndexRoute
}

const AdminsRouteChildren: AdminsRouteChildren = {
  AdminsRolesRoute: AdminsRolesRoute,
  AdminsIndexRoute: AdminsIndexRoute,
}

const AdminsRouteWithChildren =
  AdminsRoute._addFileChildren(AdminsRouteChildren)

interface DevicesRouteChildren {
  DevicesAdaptersRoute: typeof DevicesAdaptersRoute
  DevicesMonitoringRoute: typeof DevicesMonitoringRoute
  DevicesIndexRoute: typeof DevicesIndexRoute
}

const DevicesRouteChildren: DevicesRouteChildren = {
  DevicesAdaptersRoute: DevicesAdaptersRoute,
  DevicesMonitoringRoute: DevicesMonitoringRoute,
  DevicesIndexRoute: DevicesIndexRoute,
}

const DevicesRouteWithChildren =
  DevicesRoute._addFileChildren(DevicesRouteChildren)

interface PersonsRouteChildren {
  PersonsPersonIdRoute: typeof PersonsPersonIdRoute
  PersonsIndexRoute: typeof PersonsIndexRoute
}

const PersonsRouteChildren: PersonsRouteChildren = {
  PersonsPersonIdRoute: PersonsPersonIdRoute,
  PersonsIndexRoute: PersonsIndexRoute,
}

const PersonsRouteWithChildren =
  PersonsRoute._addFileChildren(PersonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessEventsRoute: AccessEventsRoute,
  AdminsRoute: AdminsRouteWithChildren,
  AlertsRoute: AlertsRoute,
  AuditLogsRoute: AuditLogsRoute,
  DashboardRoute: DashboardRoute,
  DevicesRoute: DevicesRouteWithChildren,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  PersonsRoute: PersonsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionRequestsRoute: SubscriptionRequestsRoute,
  UnavailableRoute: UnavailableRoute,
  BootstrapFirstAdminRoute: BootstrapFirstAdminRoute,
  PasswordResetConfirmRoute: PasswordResetConfirmRoute,
  PasswordResetRequestRoute: PasswordResetRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
